### ISSUE TITLE
Future plans?

### ISSUE THREAD

**Issue by webcraft** [robinsaillard/TntExpress#1]
Hi Robin! First of all, thanks for sharing your work. I'm currently in the process of integrating with TNT ExpressLabel, and this repository has already gotten me in the right direction.

I was wondering what your plans are for the future of this package. Is this something you want to keep on actively developing? Or have you moved on to something else? For getting this code to work for me, I find myself tweaking a fair amount of things, so I'm assuming this is not production ready code - which is totally fine of course.

If this is something you're planning to maintain, I can see if I can make a few pull requests with the things that are missing or incorrect for me.

**Comment by robinsaillard** [comment]
Hi Webcraft, I put this project on standby, but I will get back to it 👍
It's my project to maintain this project and you can make pull requests carefree. :)
